"""
config.py — Configurazione globale, caricamento dati e GitHub helpers.

Questo modulo è il cuore dell'app: carica i CSV, inizializza lo stato
di sessione, e fornisce funzioni per interagire con l'API GitHub.
Viene importato da main.py e da tutte le pagine.
"""

import os
import base64
import pandas as pd
import requests
import streamlit as st

# =============================================================================
# COSTANTI — Percorsi file e impostazioni app
# =============================================================================

# Titolo dell'applicazione (mostrato nel browser e nell'header)
APP_TITLE = "Sbronze Treasure Hunt"

# Directory root del progetto (dove si trova config.py / main.py)
# Usata per costruire percorsi assoluti che funzionano indipendentemente
# dalla working directory (es. Streamlit Cloud, GitHub Actions, script locali)
_ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

# Percorsi assoluti dei file CSV dati
FUNDS_FILE        = os.path.join(_ROOT_DIR, "data", "funds.csv")
TRANSACTIONS_FILE = os.path.join(_ROOT_DIR, "data", "transaction_history.csv")
HISTORICAL_FILE   = os.path.join(_ROOT_DIR, "data", "historical_data.csv")

# Percorsi relativi al repo (usati dalle GitHub API per i commit)
FUNDS_REPO_PATH        = "data/funds.csv"
TRANSACTIONS_REPO_PATH = "data/transaction_history.csv"

# Mapping colori per ciascun fondo — popolato da load_data()
FUND_COLORS: dict[str, str] = {}


# =============================================================================
# CARICAMENTO DATI — Fondi e transazioni dai CSV
# =============================================================================

@st.cache_data(ttl=300, show_spinner=False)
def load_funds_and_transactions() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Carica fondi e transazioni dai rispettivi file CSV.

    Returns:
        Tupla (funds_df, transactions_df).
        Se i file non esistono, restituisce DataFrame vuoti con le colonne corrette.
    """
    # --- Fondi ---
    if os.path.exists(FUNDS_FILE):
        funds = pd.read_csv(FUNDS_FILE)
    else:
        funds = pd.DataFrame(
            columns=["Fund", "Ticker", "ISIN", "Fund Name", "Type", "Colour"]
        )

    # --- Transazioni ---
    if os.path.exists(TRANSACTIONS_FILE):
        transactions = pd.read_csv(
            TRANSACTIONS_FILE,
            parse_dates=["Date"],
            date_format="%Y-%m-%d %H:%M:%S",
        )
    else:
        transactions = pd.DataFrame(
            columns=["Date", "Fund", "Price (€)", "Quantity", "Fees (€)"]
        )

    return funds, transactions


@st.cache_data(ttl=300, show_spinner=False)
def load_historical_prices(_funds_df: pd.DataFrame) -> pd.DataFrame:
    """Carica i prezzi storici dal file historical_data.csv generato da GitHub Actions.

    Il CSV contiene una colonna 'Date' e una colonna per ogni fondo con il
    nome del ticker. Questa funzione rinomina le colonne ticker → nome fondo
    per coerenza con il resto dell'app.

    Args:
        _funds_df: DataFrame dei fondi (per il mapping Ticker → Fund).

    Returns:
        DataFrame con colonna 'date' (datetime) e una colonna per fondo.
    """
    if not os.path.exists(HISTORICAL_FILE):
        # Diagnostica: mostra il percorso cercato e i file presenti nella directory
        data_dir = os.path.dirname(HISTORICAL_FILE)
        files_in_data = os.listdir(data_dir) if os.path.isdir(data_dir) else ["(directory not found)"]
        st.error(
            f"**{os.path.basename(HISTORICAL_FILE)}** not found.\n\n"
            f"Expected path: `{HISTORICAL_FILE}`\n\n"
            f"Files in `{data_dir}/`: {files_in_data}\n\n"
            f"CWD: `{os.getcwd()}`\n\n"
            "It is generated by GitHub Actions or by running `get_historical_data.py` locally."
        )
        return pd.DataFrame()

    try:
        df = pd.read_csv(HISTORICAL_FILE)
    except Exception as exc:
        st.error(f"Could not read {HISTORICAL_FILE}: {exc}")
        return pd.DataFrame()

    # Normalizza il nome della colonna data
    if "Date" in df.columns:
        df = df.rename(columns={"Date": "date"})

    # Converti la colonna date a datetime (già tz-naive da get_historical_data.py)
    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")

    # Rinomina colonne ticker → nome fondo (es. "0P0001CRXW.F" → "US")
    for _, row in _funds_df.iterrows():
        ticker = row["Ticker"]
        fund_name = row["Fund"]
        yahoo_col = f"{ticker}.F"
        if yahoo_col in df.columns:
            df = df.rename(columns={yahoo_col: fund_name})

    return df


# =============================================================================
# GITHUB API — Commit file via GitHub REST API
# =============================================================================

def _get_secret(name: str, default: str | None = None) -> str | None:
    """Legge un segreto da Streamlit secrets o variabili d'ambiente.

    L'ordine di priorità è:
    1. st.secrets[name]
    2. os.environ[name]
    3. default

    Args:
        name:    Nome del segreto.
        default: Valore di fallback.
    """
    try:
        return st.secrets.get(name, os.environ.get(name, default))
    except Exception:
        return os.environ.get(name, default)


# Variabili GitHub (lette una sola volta all'avvio)
GITHUB_TOKEN  = _get_secret("GITHUB_TOKEN")
GITHUB_REPO   = _get_secret("GITHUB_REPO", "donutseater97/Sbronze")
GITHUB_BRANCH = _get_secret("GITHUB_BRANCH", "main")

# Password per i ruoli utente.
#   ADMIN_PASSWORD  -> accesso completo (può editare "Add Transactions & Funds"
#                      e disattivare la privacy mode).
#   VIEWER_PASSWORD -> tutto tranne l'editing di "Add Transactions & Funds".
# OWNER_PASSWORD è mantenuto per retro-compatibilità: se ADMIN_PASSWORD non è
# impostato, si usa OWNER_PASSWORD come password admin.
OWNER_PASSWORD  = _get_secret("OWNER_PASSWORD")
ADMIN_PASSWORD  = _get_secret("ADMIN_PASSWORD", OWNER_PASSWORD)
VIEWER_PASSWORD = _get_secret("VIEWER_PASSWORD")

# Passwords are read only from real secrets:
#   - Streamlit Cloud: the app's Secrets manager (st.secrets).
#   - Local (VS Code / Codespaces): .streamlit/secrets.toml, which is
#     gitignored and therefore never committed or pushed. Only someone with
#     that local file (i.e. you) can sign in locally.
# There are NO hardcoded fallback passwords in the code, so the repo carries no
# credentials and the source of trust is the secrets file alone.


def check_role(password: str) -> str | None:
    """Restituisce il ruolo per una password: 'admin', 'viewer' o None.

    L'admin ha la precedenza: se una password combacia con entrambe (config
    errata), viene trattata come admin.
    """
    if password and ADMIN_PASSWORD and password == ADMIN_PASSWORD:
        return "admin"
    if password and VIEWER_PASSWORD and password == VIEWER_PASSWORD:
        return "viewer"
    return None


def github_get_file_sha(path: str) -> str | None:
    """Recupera lo SHA di un file nel repository GitHub.

    Necessario per aggiornare un file esistente via API.

    Args:
        path: Percorso del file nel repo (es. 'data/funds.csv').

    Returns:
        SHA del file, o None se non trovato / errore.
    """
    if not GITHUB_TOKEN or not GITHUB_REPO:
        return None
    url = f"https://api.github.com/repos/{GITHUB_REPO}/contents/{path}"
    params = {"ref": GITHUB_BRANCH}
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
    }
    resp = requests.get(url, headers=headers, params=params, timeout=30)
    if resp.status_code == 200:
        return resp.json().get("sha")
    return None


def github_put_file(path: str, content_str: str, message: str) -> bool:
    """Crea o aggiorna un file nel repository GitHub via API.

    Codifica il contenuto in base64, recupera lo SHA (se il file esiste)
    e invia una richiesta PUT per committare la modifica.

    Args:
        path:        Percorso del file nel repo.
        content_str: Contenuto del file come stringa.
        message:     Messaggio di commit.

    Returns:
        True se il commit è andato a buon fine, False altrimenti.
    """
    if not GITHUB_TOKEN or not GITHUB_REPO:
        return False
    url = f"https://api.github.com/repos/{GITHUB_REPO}/contents/{path}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
    }
    sha = github_get_file_sha(path)
    data = {
        "message": message,
        "content": base64.b64encode(content_str.encode("utf-8")).decode("ascii"),
        "branch": GITHUB_BRANCH,
    }
    if sha:
        data["sha"] = sha
    resp = requests.put(url, headers=headers, json=data, timeout=30)
    return 200 <= resp.status_code < 300